.catalog:
  name: "Rancher Container CrontabFR"
  version: "v0.3.1"
  description: "Service that will start, stop or restart containers"
  minimum_rancher_version: v1.5.0
  questions:
    - variable: metrics
      type: enum
      label: Enable Metrics Endpoint
      description: |
        <container>:9191/metrics will be available for Prometheus scraping.
      default: false
      options:
        - true
        - false
    - variable: debug
      type: enum
      default: false
      options:
        - true
        - false
      label: Enable Debug
      
