name: Rancher Container CronFR
description: |
  Rancher Container Crontab starts, stops or restarts containers 
version: v0.3.1
category: Framework
labels:
  io.rancher.orchestration.supported: 'cattle'
